// pages/terms-of-service.vue
<template>
  <main>
    <h1>Fyreplace terms of service</h1>
    <h2 id="user-content">User generated content</h2>
    <p>
      Content submitted to Fyreplace is owned solely by the holder of the
      account uploading it. Responsibility for uploaded content falls onto
      said account holder. Fyreplace developers/moderators may not be held
      responsible for the content published on the platform.
    </p>
    <h2 id="content-allowed">Content allowed on the platform</h2>
    <p>
      By creating an account, you agree to abide by the following rules and
      guidelines at all times when using the platform. The following types of
      content are forbidden on the platform:
    </p>
    <ul>
      <li>
        <strong>Illegal content</strong>
        <br />
        As data is stored in Germany, allowed content is bounded by German
        law.
      </li>
      <li>
        <strong>Irrespectful content</strong>
        <br />
        No amount of bullying, harrassement, discrimination based on
        ethnicity, personal beliefs/opinions, gender, sexual orientation, is
        allowed. This list is not meant to be exhaustive. In simple terms: be
        nice to each other.
      </li>
      <li>
        <strong>Violent, graphic imagery</strong>
        <br />
        An exception may apply to ongoing, current events.
      </li>
      <li>
        <strong>Explicit sexual content</strong>
        <br />
        Better suited alternatives exist and shall be preferred for browsing
        and sharing this type of content.
      </li>
    </ul>
    This list is not meant to be exhaustive. What behavior is considered okay
    and what is not is left at the discretion of the moderators. While it is
    understandable that a precise, complete list is easier to follow, a
    general direction should be enough; and lists can never account for more
    nuanced or subjective matters.
    <br />
    If you are currently reading this document because you are unsure of what
    you can post or not, you can always <nuxt-link href="/contact">get in touch</nuxt-link>!
    <h2 id="moderation">Bans and account termination</h2>
    Failure to comply to the rules may result in a temporary or full ban,
    depending on the severity of the offense. Fyreplace is meant to be a
    welcoming place where everyone can feel at ease.
    <br />
    If you believe you have been victim of an abusive ban decision,
    <nuxt-link href="/contact">please get in contact</nuxt-link>.

    <Head>
      <Title>Terms of service</Title>
    </Head>
  </main>
</template>

// src/routes/(information)/terms-of-service/+page.svelte
<svelte:head>
  <title>Terms of service</title>
</svelte:head>

<main>
  <h1>Fyreplace terms of service</h1>
  <h2 id="user-content">User generated content</h2>
  <p>
    Content submitted to Fyreplace is owned solely by the holder of the account uploading it.
    Responsibility for uploaded content falls onto said account holder. Fyreplace
    developers/moderators may not be held responsible for the content published on the platform.
  </p>
  <h2 id="content-allowed">Content allowed on the platform</h2>
  <p>
    By creating an account, you agree to abide by the following rules and guidelines at all times
    when using the platform. The following types of content are forbidden on the platform:
  </p>
  <ul>
    <li>
      <strong>Illegal content</strong>
      <br />
      As data is stored in Germany, allowed content is bounded by German law.
    </li>
    <li>
      <strong>Irrespectful content</strong>
      <br />
      No amount of bullying, harrassement, discrimination based on ethnicity, personal beliefs/opinions,
      gender, sexual orientation, is allowed. This list is not meant to be exhaustive. In simple terms:
      be nice to each other.
    </li>
    <li>
      <strong>Violent, graphic imagery</strong>
      <br />
      An exception may apply to ongoing, current events.
    </li>
    <li>
      <strong>Explicit sexual content</strong>
      <br />
      Better suited alternatives exist and shall be preferred for browsing and sharing this type of content.
    </li>
  </ul>
  This list is not meant to be exhaustive. What behavior is considered okay and what is not is left at
  the discretion of the moderators. While it is understandable that a precise, complete list is easier
  to follow, a general direction should be enough; and lists can never account for more nuanced or subjective
  matters.
  <br />
  If you are currently reading this document because you are unsure of what you can post or not, you
  can always <a href="/contact">get in touch</a>!
  <h2 id="moderation">Bans and account termination</h2>
  Failure to comply to the rules may result in a temporary or full ban, depending on the severity of
  the offense. Fyreplace is meant to be a welcoming place where everyone can feel at ease.
  <br />
  If you believe you have been victim of an abusive ban decision,
  <a href="/contact">please get in contact</a>.
</main>
