// pages/contact.vue
<template>
  <main>
    <h1>Contact</h1>
    <p>
      For any question or inquiries, leave a message at
      <nuxt-link href="mailto:Fyreplace &lt;hello@fyreplace.app&gt;">hello@fyreplace.app</nuxt-link>.
    </p>
    <h2>Abuse</h2>
    <p>
      For reports of abuse, leave a message at
      <nuxt-link href="mailto:Fyreplace &lt;abuse@fyreplace.app&gt;">abuse@fyreplace.app</nuxt-link>.
    </p>

    <Head>
      <Title>Contact</Title>
    </Head>
  </main>
</template>

// src/routes/(information)/contact/+page.svelte
<svelte:head>
	<title>Contact</title>
</svelte:head>

<main>
	<h1>Contact</h1>
	<p>
		For any question or inquiries, leave a message at
		<a href="mailto:Fyreplace <hello@fyreplace.app>">hello@fyreplace.app</a>.
	</p>
	<h2>Abuse</h2>
	<p>
		For reports of abuse, leave a message at
		<a href="mailto:Fyreplace <abuse@fyreplace.app>">abuse@fyreplace.app</a>.
	</p>
</main>
